### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by grusirna** [roverdotcom/django-delayed-union#10]
class DelayedQuerySet(metaclass=DelayedQuerySetBase):
    def __init__(self, *querysets, **kwargs):
        if not all(isinstance(qs, QuerySet) for qs in querysets):
        self._querysets = tuple(qs for qs in querysets)

change qs.order_by() to qs for queryset slice

**Comment by mwhansen** [comment]
Hello @grusirna!  Could you give some more information as to what you're trying to do?  Is it to preserve the ordering within the component querysets? 

Only some of the database backends support ordering within the component querysets (see `supports_slicing_ordering_in_compound`).
